### ISSUE TITLE
Unirest in throws errors in smoke tests

### ISSUE THREAD

**Issue by philipithomas** [Staffjoy/suite#3]
```
Traceback (most recent call last):
  File "/opt/python/2.7.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/python/2.7.12/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/unirest/__init__.py", line 82, in __request
    encoded_string = base64.b64encode(user + ':' + password)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by philipithomas** [comment]
See https://travis-ci.org/Staffjoy/suite/builds/205335397

**Comment by isaacm** [comment]
I think this error is caused by sending events to intercom.io [here](https://github.com/Staffjoy/suite/blob/master/app/models/user_model.py#L200-L206).

If no tracking needs to happen during testing, then checking `current_app.config.get("ENV") in ["dev", "test"]` [here](https://github.com/Staffjoy/suite/blob/master/app/models/user_model.py#L176) should prevent the call to intercom.io API while running smoke tests.
