### ISSUE TITLE
Exception on /favicon.ico / 502 Bad Gateway

### ISSUE THREAD

**Issue by mikepaszkiewicz** [Staffjoy/suite#43]
I think I mucked up something with the assets file here...

ERROR Exception on /favicon.ico [GET] Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app     response = self.full_dispatch_request()   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request     rv = self.handle_user_exception(e)   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router     return original_handler(e)   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1370, in handle_user_exception     return self.handle_http_exception(e)   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1330, in handle_http_exception     return handler(e)   File "./app/__init__.py", line 173, in page_not_found     resp = make_response(render_template("404.html"))   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template     context, ctx.app)   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render     rv = template.render(context)   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render     return self.environment.handle_exception(exc_info, True)   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception     reraise(exc_type, exc_value, tb)   File "/src/app/templates/404.html", line 1, in top-level template code     {% extends "error.html" %}   File "/src/app/templates/error.html", line 1, in top-level template code     {% extends "bootstrap.html" %}   File "/src/app/templates/bootstrap.html", line 74, in top-level template code     {% block intercom %}   File "/src/app/templates/bootstrap.html", line 76, in block "intercom"     window.intercomSettings = {{ current_user.intercom_settings() | safe }};   File "./app/models/user_model.py", line 488, in intercom_settings     hashlib.sha256, ).hexdigest(),   File "/usr/lib/python2.7/hmac.py", line 133, in new     return HMAC(key, msg, digestmod)   File "/usr/lib/python2.7/hmac.py", line 68, in __init__     if len(key) > blocksize: TypeError: object of type 'NoneType' has no len()

**Comment by mikepaszkiewicz** [comment]
awesome, did the trick!
